# Model setup
DAC.sample_rate: 24000
DAC.encoder_dim: 64
DAC.encoder_rates: [2, 4, 8, 8]
DAC.decoder_dim: 1536
DAC.decoder_rates: [8, 8, 4, 2]

# Quantization
DAC.n_codebooks: 1
DAC.codebook_size: 955000
DAC.codebook_dim: 8
DAC.quantizer_dropout: 1.0

# Discriminator
Discriminator.sample_rate: 24000
Discriminator.rates: []
Discriminator.periods: [2, 3, 5, 7, 11]
Discriminator.fft_sizes: [2048, 1024, 512]
Discriminator.bands:
  - [0.0, 0.1]
  - [0.1, 0.25]
  - [0.25, 0.5]
  - [0.5, 0.75]
  - [0.75, 1.0]

# Optimization
AdamW.betas: [0.8, 0.99]
AdamW.lr: 0.0001
ExponentialLR.gamma: 0.999996

amp: false
val_batch_size: 100
device: cuda
num_iters: 400000
save_iters: [10000, 50000, 100000, 200000]
valid_freq: 1000
sample_freq: 10000
num_workers: 32
val_idx: [0, 1, 2, 3, 4, 5, 6, 7]
seed: 0
lambdas:
  mel/loss: 15.0
  adv/feat_loss: 2.0
  adv/gen_loss: 1.0
  vq/commitment_loss: 0.25
  vq/codebook_loss: 1.0

VolumeNorm.db: [const, -16]

# Transforms
build_transform.preprocess:
  - Identity
build_transform.augment_prob: 0.0
build_transform.augment:
  - Identity
build_transform.postprocess:
  - VolumeNorm
  - RescaleAudio
  - ShiftPhase

# Loss setup
MultiScaleSTFTLoss.window_lengths: [2048, 512]
MelSpectrogramLoss.n_mels: [5, 10, 20, 40, 80, 160, 320]
MelSpectrogramLoss.window_lengths: [32, 64, 128, 256, 512, 1024, 2048]
MelSpectrogramLoss.mel_fmin: [0, 0, 0, 0, 0, 0, 0]
MelSpectrogramLoss.mel_fmax: [null, null, null, null, null, null, null]
MelSpectrogramLoss.pow: 1.0
MelSpectrogramLoss.clamp_eps: 1.0e-5
MelSpectrogramLoss.mag_weight: 0.0

# Data
batch_size: 100
train/AudioDataset.duration: 0.38
train/AudioDataset.n_examples: 10000000

val/AudioDataset.duration: 5.0
val/build_transform.augment_prob: 1.0
val/AudioDataset.n_examples: 250

test/AudioDataset.duration: 10.0
test/build_transform.augment_prob: 1.0
test/AudioDataset.n_examples: 1000

AudioLoader.shuffle: true
AudioDataset.without_replacement: true

train/build_dataset.folders:
  speech_fb:
    - /ephemeral_volume/ramon/data/proc/train/speech/dap
  speech_hq:
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/vctk_wav48_silence_trimmed
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/VocalSet_48kHz_mono
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/read_speech
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/french_speech

  speech_uq:
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/emotional_speech
    - /ephemeral_volume/ramon/data/raw/speech/common_voice_17_0
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/german_speech
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/russian_speech
    - /ephemeral_volume/ramon/data/raw/speech/dns_4/datasets_fullband/clean_fullband/spanish_speech

  music_hq:
    - /ephemeral_volume/ramon/data/raw/music/musdb/train
  music_uq:
    - /ephemeral_volume/ramon/data/raw/music/jamendo
  general:
    - /ephemeral_volume/ramon/data/raw/env/audioset/balanced_train
    - /ephemeral_volume/ramon/data/raw/env/audioset/unbalanced_train

val/build_dataset.folders:
  speech_hq:
    - /ephemeral_volume/ramon/data/proc/val/speech/dap
  music_hq:
    - /ephemeral_volume/ramon/data/raw/music/musdb/test
  general:
    - /ephemeral_volume/ramon/data/raw/env/audioset/eval

test/build_dataset.folders:
  speech_hq:
    - /ephemeral_volume/ramon/data/proc/val/speech/dap
  music_hq:
    - /ephemeral_volume/ramon/data/raw/music/musdb/test
  general:
    - /ephemeral_volume/ramon/data/raw/env/audioset/eval
